add mail client
JenBytowski/content-distribution-system pull request #5
Opened 2023-07-04 11:19 UTC by Bad1m

2023-07-04 13:51 UTC, JenBytowski requested changes

2023-07-04 13:51 UTC, JenBytowski commented on DistributionSystemApi/DistributionSystemApi/MailLibrary/MailLibrary.sln
> +Global
I dont think that we need to add another solution for library. Please just add new library project to existing solution

2023-07-04 13:51 UTC, JenBytowski commented on DistributionSystemApi/DistributionSystemApi/MailLibrary/MailLibrary/MailModel.cs
> +        public List<string> Attachments { get; set; } = new List<string>();
we also need to support binary attachments like files, pictures and etc

2023-07-04 13:51 UTC, JenBytowski commented on DistributionSystemApi/DistributionSystemApi/MailLibrary/MailLibrary/SMTPMailService.cs
> +    public class SMTPMailService : IMailValidationService, IDisposable
what is the purpose to realize IMailValidationService interface in class which should send mails? Its an violation of SOLID principles

2023-07-04 13:51 UTC, JenBytowski commented on DistributionSystemApi/DistributionSystemApi/MailLibrary/MailLibrary/SMTPMailService.cs
> +        public async Task SendEmailAsync(MailModel mail)
I think its important thing to have possibility to cancel long running task, so please add CancellationToken to interface

2023-07-04 13:51 UTC, JenBytowski commented on DistributionSystemApi/DistributionSystemApi/MailLibrary/MailLibrary/SMTPMailService.cs
> +                    mail.To.ForEach(recipient => mailMessage.To.Add(new MailAddress(recipient)));
.ForEach extension method is much slower that foreach statement, so please use it instead

2023-07-04 13:51 UTC, JenBytowski commented on DistributionSystemApi/DistributionSystemApi/MailLibrary/MailLibrary/SMTPMailService.cs
> +                    mailMessage.From = new MailAddress(mail.From);
what would happen if I left mail.From as null?

2023-07-04 13:51 UTC, JenBytowski commented on DistributionSystemApi/DistributionSystemApi/MailLibrary/MailLibrary/SMTPMailService.cs
> +                throw new ArgumentException(InvalidEmaisSendExceptionMessage + ex.Message);
by doing this you will last part of exception stacktrace

2023-07-04 13:51 UTC, JenBytowski commented on DistributionSystemApi/DistributionSystemApi/MailLibrary/MailLibrary/SMTPMailService.cs
> +        public void Dispose()
if you dont create a IDisposable member by you own, then you dont need to manage its state. Code which creates it should manage its lifetime

2023-07-04 13:51 UTC, JenBytowski commented on DistributionSystemApi/DistributionSystemApi/MailLibrary/MailLibrary/IMailValidationService.cs
> +﻿
why do you need those blank lines?)

2023-07-05 11:39 UTC, JenBytowski requested changes

2023-07-05 11:39 UTC, JenBytowski commented on DistributionSystemApi/MailLibrary/SMTPMailService.cs
> +                    mailMessage.Subject = mail.Subject;
it would be great to incapsulate this mapping logic to another method, which creates an instance of MailMessage. Also please use 'var' keyword everywhere its possible

2023-07-05 11:39 UTC, JenBytowski commented on DistributionSystemApi/MailLibrary/SMTPMailService.cs
> +            if (mail.From == null)
when you are want to compare string to null please use static method 'string.IsNullOrEmpty' instead

2023-07-05 11:39 UTC, JenBytowski commented on DistributionSystemApi/DistributionSystemApi/MailTest.cs
> +        public async void TestSend()
please delete this file if it was created for test purpose, or better create new test project and write several test cases for this service(if you have any questions here, contact me and we will discuss)

2023-07-05 11:39 UTC, JenBytowski commented on DistributionSystemApi/DistributionSystemApi/Program.cs
>  app.MapRazorPages();
please add your services to DI

2023-07-05 11:39 UTC, JenBytowski commented on DistributionSystemApi/MailLibrary/AttachmentData.cs
> +{
would be grate if you replace models to their own folder

2023-07-05 11:39 UTC, JenBytowski commented on DistributionSystemApi/MailLibrary/IMailService.cs
> +    public interface IMailService<MailModel>
I dont think that you need to use generics here, if you have any questions or concerns we can discuss it

2023-07-05 11:39 UTC, JenBytowski commented on DistributionSystemApi/MailLibrary/SMTPMailService.cs
> +                {
better dispose this object by yourself using try catch finally statement

2023-07-05 11:39 UTC, JenBytowski commented on DistributionSystemApi/MailLibrary/SMTPMailService.cs
> +
better create MailMessage object in this method using MailModel object as source

2023-07-05 11:39 UTC, JenBytowski commented on DistributionSystemApi/MailLibrary/MailValidationService.cs
> +                throw new ArgumentException(InvalidEmailsSenderExceptionMessage);
I think we also need to validate attachments here

2023-07-05 11:39 UTC, JenBytowski commented on DistributionSystemApi/MailLibrary/DistributionSystemApi.MailLibrary.csproj
> +    <TargetFramework>net6.0</TargetFramework>
also please add an extension which registers all important services in service collection

2023-07-07 15:32 UTC, JenBytowski commented on DistributionSystemApi/DistributionSystemApi.MailLibrary/Models/SmtpSettings.cs
> +        public string Host { get; set; }
please add new lines between functions(aka properties)

2023-07-07 15:35 UTC, JenBytowski commented on DistributionSystemApi/DistributionSystemApi.MailLibrary/Models/EmailModel.cs
> +        public bool IsValidAddress(string address)
Does this method should be public?

2023-07-07 15:35 UTC, JenBytowski commented on DistributionSystemApi/DistributionSystemApi.MailLibrary/MailServiceExtensions.cs
> +        private static SmtpClient CreateSmtpClient(IConfiguration configuration)
why did you decide to use static keyword here?

2023-07-10 09:34 UTC, JenBytowski approved these changes

2023-07-11 09:08 UTC, EugeneSeledtsov approved these changes

2023-07-11 09:08 UTC, merged