stylecop added
JenBytowski/content-distribution-system pull request #7
Opened 2023-07-07 09:55 UTC by Roma-Jivchik

2023-07-07 10:01 UTC, JenBytowski requested changes

2023-07-07 10:01 UTC, JenBytowski commented on DistributionSystemApi/DistributionSystemApi/stylecop-config.ruleset
> +<RuleSet Name="Microsoft Managed Recommended Rules" Description="These rules focus on the most critical problems in your code, including potential security holes, application crashes, and other impor
it will not work without extension for visual studio or without special nuget package for projects. As for me I dont have this extension...

2023-07-07 10:01 UTC, JenBytowski commented on DistributionSystemApi/DistributionSystemApi/stylecop-config.ruleset
> +    <Description Resource="MinimumRecommendedRules_Description" />
Also have you discussed those settings with @Bad1m?

2023-07-10 09:11 UTC, JenBytowski approved these changes

2023-07-10 12:58 UTC, EugeneSeledtsov approved these changes

2023-07-10 13:29 UTC, merged